//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STATIONERY_MANAGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.orders_item = new HashSet<orders_item>();
        }
    
        public int id { get; set; }
        public string bill_no { get; set; }
        public string customer_name { get; set; }
        public string customer_address { get; set; }
        public string customer_phone { get; set; }
        public string date_time { get; set; }
        public double gross_amount { get; set; }
        public double service_charge_rate { get; set; }
        public double service_charge { get; set; }
        public double vat_charge_rate { get; set; }
        public double vat_charge { get; set; }
        public double net_amount { get; set; }
        public double discount { get; set; }
        public int paid_status { get; set; }
        public int user_id { get; set; }
        public int company_id { get; set; }
    
        public virtual company company { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders_item> orders_item { get; set; }
    }
}
